cd ..\caret_cifti
nmake %1
cd ..\caret_brain_set
nmake %1
cd ..\caret_common
nmake %1
cd ..\caret_gifti
nmake %1
cd ..\caret_command_operations 
nmake %1
cd ..\caret_statistics
nmake %1
cd ..\caret_vtk4_classes
nmake %1
cd ..\caret_uniformize
nmake %1
cd ..\caret_files
nmake %1
cd ..\caret_widgets
nmake %1
cd ..\caret_command
nmake %1
cd ..\caret_edit
nmake %1
cd ..\caret
nmake %1
cd ..\windows
