#! /bin/sh -e

# Copyright (C) 2007 by
# Michael Hanke        michael.hanke@gmail.com
#
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


if [ "${0##*/}" = "caret_app_wrapper" ]; then
	echo 'caret_app_wrapper: This script should not be run like this, see caret(1) for details' 1>&2
	exit 1
fi

# setup library search path for carets internal libs and Qt4 plugins
LD_LIBRARY_PATH=/usr/lib/caret/lib/:/usr/lib/qt4/plugins/imageformats \
CARET5_HOME=/usr/share/caret \
CARET_WEB_BROWSER=/etc/alternatives/x-www-browser \
CARET_ATLAS_DIRECTORIES=/usr/share/caret/data_files/fmri_mapping_files \
exec /usr/lib/caret/bin/${0##*/} $@

