.TH "CARET" "1" "December 2007" "Michael Hanke" ""
.SH "NAME"
caret \- interactive viewing, manipulation and analysis of surface
reconstructions of the cerebral and cerebellar cortex
.SH "DESCRIPTION"
Caret is a software application for viewing and manipulating surface
reconstructions of the cerebral and cerebellar cortex, viewing volumes, for
displaying experimental data on the surfaces and volumes and performing
functional and structural analysis of the cerebral cortex.
.PP
Besides the main GUI application, the Caret software package provides a
command line interface \fBcaret_command\fR that significantly improves
the efficiency when analyzing a large number of datasets.

.PP
\fBcaret_command\fR provides an extensive help output when called with
the \fI-help\fR option.
.PP
Questions regarding the usage of \fBCaret\fR or related theory can be posted on the 
\fBCaret mailing list\fR (see \fIhttp://brainvis.wustl.edu/caret/#Help\fR).

.SH "SEE ALSO"
The Caret homepage at
.I http://brainvis.wustl.edu/caret
which provides extensive documentation, including tutorials and demo datasets.
.SH "AUTHOR"
\fBCaret\fR was written by John Harwell, Heather Drury, Donna Hanlon and David Van Essen;
Washington University School of Medicine
.PP 
This manual page was written by Michael Hanke <michael.hanke@gmail.com>,
for the Debian project (but may be used by others).
