.TH "CARET" "1" "September 2007" "Michael Hanke" ""
.SH "NAME"
caret \- interactive viewing, manipulation and analysis of surface reconstructions of the cerebral and cerebellar cortex
.SH "DESCRIPTION"
Caret is a software application for viewing and manipulating surface reconstructions of
the cerebral and cerebellar cortex, viewing volumes, for displaying experimental data on
the surfaces and volumes and performing functional and structural analysis of the
cerebral cortex.
.PP
Besides the main GUI application, the Caret software package provides a number of command
line tools that significantly improve the efficiency when analyzing a large number of
datasets. The following programs are provided:
.IP \fIcaret5\fR:
visualize cerebral and cerebellar cortical maps.

.IP \fIcaret_copy_spec\fR:
copy SPEC files optionally including data files to a new location or SPEC file.

.IP \fIcaret_file_convert\fR:
convert Caret data files from and to a number of text and binary formats.

.IP \fIcaret_metric\fR:
performs numerical operations on metric datasets.

.IP \fIcaret_command\fR:
command line interface to most of the functionality provided by the GUI.

.IP \fIcaret_edit\fR:
simple text editor with cross-platform support for different line feeds.

.IP \fIcaret_map_fmri\fR:
maps function volume(s) to nodes in one surface. The output is placed in a metric file.

.IP \fIcaret_zip_spec\fR:
compress a SPEC file and all referenced datasets.

.PP
All of the programs listed above provide extensive help output when called with
the \fI-help\fR option.
.PP
Questions regarding the usage of \fBCaret\fR or related theory can be posted on the 
\fBCaret mailing list\fR (see \fIhttp://brainvis.wustl.edu/caret/#Help\fR).

.SH "SEE ALSO"
The Caret homepage at
.I http://brainvis.wustl.edu/caret
which provides extensive documentation, including tutorials and demo datasets.
.SH "AUTHOR"
\fBCaret\fR was written by John Harwell, Heather Drury, Donna Hanlon and David Van Essen;
Washington University School of Medicine
.PP 
This manual page was written by Michael Hanke <michael.hanke@gmail.com>,
for the Debian project (but may be used by others).
